[build]
builder = "NIXPACKS"

[build.cmd]
buildCommand = "npm install && npx vite build && npx tsc -p server/tsconfig.json --noEmitOnError false && cp vite.config.js dist/ && sed -i 's|../vite.config\"|../vite.config.js\"|g' dist/server/vite.js"

[deploy]
startCommand = "NODE_ENV=production node dist/server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "$PORT"