[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "vendzz-platform"

[services.source]
repo = "brunoxkz1337/v-platform"
branch = "main"

[services.variables]
NODE_ENV = "production"
PORT = "${{ PORT }}"
DATABASE_URL = "${{ DATABASE_URL }}"
SESSION_SECRET = "${{ RAILWAY_GEN_SECRET }}"
JWT_SECRET = "${{ RAILWAY_GEN_SECRET }}"
REFRESH_JWT_SECRET = "${{ RAILWAY_GEN_SECRET_2 }}"
VITE_API_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}"

[services.build]
buildCommand = "npm install && npm run build"
startCommand = "npm start"

[services.healthcheck]
path = "/api/health"
timeout = 30