[build]
builder = "NIXPACKS"

[build.cmd]
buildCommand = "npm install && npx vite build && npx tsc -p server/tsconfig.json"

[deploy]
startCommand = "NODE_ENV=production node dist/server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "$PORT"