import { useState, useEffect, createContext, useContext } from "react";

interface LanguageContextType {
  currentLanguage: string;
  changeLanguage: (language: string) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for when used outside provider
    const [currentLanguage, setCurrentLanguage] = useState(() => {
      return localStorage.getItem('language') || 'pt-BR';
    });

    const changeLanguage = (language: string) => {
      setCurrentLanguage(language);
      localStorage.setItem('language', language);
      // Trigger page reload to apply translations
      window.location.reload();
    };

    const t = (key: string, params?: Record<string, string>) => {
      return getTranslation(key, currentLanguage, params);
    };

    return { currentLanguage, changeLanguage, t };
  }
  return context;
}

// Translation function
function getTranslation(key: string, language: string, params?: Record<string, string>): string {
  const translations: Record<string, Record<string, string>> = {
    'pt-BR': {
      // Sidebar
      'dashboard': 'Dashboard',
      'create_quiz': 'Criar Quiz',
      'my_quizzes': 'Meus Quizzes',
      'analytics': 'Analytics',
      'real_time_analytics': 'Analytics em Tempo Real',
      'email_marketing': 'Email Marketing',
      'sms_campaigns': 'Campanhas SMS',
      'whatsapp_automation': 'Automação WhatsApp',
      'cloaker': 'Cloaker',
      'upgrade': 'Upgrade',
      'settings': 'Configurações',
      'awards': 'Premiações',
      'current_plan': 'Plano Atual',
      'quizzes_created': 'quizzes criados',
      'unlimited': 'ilimitado',
      'quizzes_used': 'quizzes utilizados',
      
      // Dashboard
      'welcome_back': 'Bem-vindo de volta!',
      'dashboard_subtitle': 'Acompanhe o desempenho dos seus quizzes',
      'total_quizzes': 'Total de Quizzes',
      'total_views': 'Total de Visualizações',
      'total_leads': 'Total de Leads',
      'conversion_rate': 'Taxa de Conversão',
      'your_quizzes': 'Seus Quizzes',
      'quick_buttons': 'Botões Rápidos',
      'create_quiz_btn': 'Criar Quiz',
      'view_analytics': 'Ver Analytics',
      'tutorials': 'Tutoriais',
      'plans': 'Planos',
      'marketing_automation': 'Automação de Marketing',
      'email_campaigns': 'Campanhas Email',
      'sms_marketing': 'Marketing SMS',
      'whatsapp_campaigns': 'Campanhas WhatsApp',
      'quick_actions': 'Ações Rápidas',
      'import_contacts': 'Importar Contatos',
      'export_data': 'Exportar Dados',
      'integrations': 'Integrações',
      'api_settings': 'Configurações API',
      
      // Common
      'loading': 'Carregando...',
      'error': 'Erro',
      'success': 'Sucesso',
      'cancel': 'Cancelar',
      'save': 'Salvar',
      'delete': 'Deletar',
      'edit': 'Editar',
      'view': 'Visualizar',
      'create': 'Criar',
      'update': 'Atualizar',
      'search': 'Pesquisar',
      'filter': 'Filtrar',
      'sort': 'Ordenar',
      'export': 'Exportar',
      'import': 'Importar',
      'close': 'Fechar',
      'open': 'Abrir',
      'yes': 'Sim',
      'no': 'Não',
      'back': 'Voltar',
      'next': 'Próximo',
      'previous': 'Anterior',
      'finish': 'Finalizar',
      'continue': 'Continuar',
      
      // Notifications
      'welcome_notification': 'Bem-vindo ao Vendzz!',
      'account_created': 'Sua conta foi criada com sucesso. Explore as funcionalidades da plataforma.',
      'system_updated': 'Sistema atualizado',
      'new_version_available': 'Nova versão disponível com melhorias de performance.',
      'sms_credits': 'Créditos SMS',
      'credits_available': 'Você tem {credits} créditos SMS disponíveis para suas campanhas.',
      'remarketing_sms': 'Remarketing SMS',
      
      // Dashboard page
      'total_credits': 'Total de Créditos',
      'total_campaigns': 'Total de Campanhas',
      'campaign_performance': 'Performance de Campanhas',
      'recent_activity': 'Atividade Recente',
      'welcome_back_pt': 'Bem-vindo de volta',
      'sms_campaigns_pt': 'Campanhas SMS',
      'whatsapp_campaigns_pt': 'Campanhas WhatsApp',
      'email_campaigns_pt': 'Campanhas Email',
      'view_all': 'Ver Todos',
      'create_new': 'Criar Novo',
      'no_quizzes': 'Nenhum quiz criado ainda',
      'create_your_first_quiz': 'Crie seu primeiro quiz para começar a capturar leads',
      'quiz_performance': 'Performance dos Quizzes',
      'leads_captured': 'Leads Capturados',
      'completion_rate': 'Taxa de Conclusão',
      'average_time': 'Tempo Médio',
      'top_performing': 'Melhor Performance',
      'views': 'Visualizações',
      'responses': 'Respostas',
      'edit_quiz': 'Editar Quiz',
      'view_quiz': 'Visualizar Quiz',
      'share_quiz': 'Compartilhar Quiz',
      'delete_quiz': 'Excluir Quiz',
      'copy_link': 'Copiar Link',
      'quiz_analytics': 'Analytics do Quiz',
      'marketing_tools': 'Ferramentas de Marketing',
      'quick_actions_pt': 'Ações Rápidas',
      'create_campaign': 'Criar Campanha',
      'send_sms': 'Enviar SMS',
      'send_email': 'Enviar Email',
      'send_whatsapp': 'Enviar WhatsApp',
      'total_quizzes_pt': 'Quizzes',
      'conversion_rate_pt': 'Taxa de Conversão',
      'your_quizzes_title': 'Seus Quizzes',
      'manage_and_monitor': 'Gerencie e monitore performance',
      'start_your_journey': 'Comece sua jornada',
      'create_first_quiz_desc': 'Crie seu primeiro quiz para começar a capturar leads qualificados e impulsionar seu negócio',
      'create_first_quiz': 'Criar Primeiro Quiz',
      'published': 'Publicado',
      'draft': 'Rascunho',
      'leads': 'Leads',
      'view_preview': 'Visualizar Preview',
      'copy_url': 'Copiar URL',
      'quizzes_count': 'quizzes',
      'duplicate_quiz': 'Duplicar Quiz',
      'copy_public_url': 'Copiar URL Pública',
      'view_all_quizzes': 'Ver Todos os Quizzes',
      'direct_access_main_features': 'Acesso direto às principais funcionalidades',
      'multichannel_campaigns': 'Campanhas multi-canal para conversão',
      
      // Quizzes page
      'manage_your_quizzes': 'Gerencie seus quizzes e monitore o desempenho',
      'search_quizzes': 'Pesquisar por título ou descrição...',
      'all': 'Todos',
      'drafts': 'Rascunhos',
      'filter_by_status': 'Filtrar por status',
      'grid_view': 'Visualização em Grade',
      'list_view': 'Visualização em Lista',
      'no_quizzes_found': 'Nenhum quiz encontrado',
      'create_your_first': 'Crie seu primeiro quiz para começar',
      'get_started': 'Começar',
      'created_at': 'Criado em',
      'last_updated': 'Última atualização',
      'total': 'Total',
      'active': 'ativos',
      'in_progress': 'em andamento',
    },
    'en-US': {
      // Sidebar
      'dashboard': 'Dashboard',
      'create_quiz': 'Create Quiz',
      'my_quizzes': 'My Quizzes',
      'analytics': 'Analytics',
      'real_time_analytics': 'Real-time Analytics',
      'email_marketing': 'Email Marketing',
      'sms_campaigns': 'SMS Campaigns',
      'whatsapp_automation': 'WhatsApp Automation',
      'cloaker': 'Cloaker',
      'upgrade': 'Upgrade',
      'settings': 'Settings',
      'awards': 'Awards',
      'unlimited': 'unlimited',
      'quizzes_used': 'quizzes used',
      
      // Dashboard
      'dashboard_subtitle': 'Track your quiz performance',
      'total_quizzes': 'Total Quizzes',
      'total_views': 'Total Views',
      'total_leads': 'Total Leads',
      'conversion_rate': 'Conversion Rate',
      'your_quizzes': 'Your Quizzes',
      'quick_buttons': 'Quick Buttons',
      'create_quiz_btn': 'Create Quiz',
      'view_analytics': 'View Analytics',
      'tutorials': 'Tutorials',
      'plans': 'Plans',
      'marketing_automation': 'Marketing Automation',
      'email_campaigns': 'Email Campaigns',
      'sms_marketing': 'SMS Marketing',
      'whatsapp_campaigns': 'WhatsApp Campaigns',
      'quick_actions': 'Quick Actions',
      'import_contacts': 'Import Contacts',
      'export_data': 'Export Data',
      'integrations': 'Integrations',
      'api_settings': 'API Settings',
      
      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'view': 'View',
      'create': 'Create',
      'update': 'Update',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'export': 'Export',
      'import': 'Import',
      'close': 'Close',
      'open': 'Open',
      'yes': 'Yes',
      'no': 'No',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'finish': 'Finish',
      'continue': 'Continue',
      
      // Notifications
      'welcome_notification': 'Welcome to Vendzz!',
      'account_created': 'Your account has been created successfully. Explore the platform features.',
      'system_updated': 'System Updated',
      'new_version_available': 'New version available with performance improvements.',
      'sms_credits': 'SMS Credits',
      'credits_available': 'You have {credits} SMS credits available for your campaigns.',
      'remarketing_sms': 'SMS Remarketing',
      'templates': 'Templates',
      'admin': 'Admin',
      'current_plan_en': 'Current Plan',
      'upgrade_en': 'Upgrade',
      'settings_en': 'Settings',
      'credits_en': 'Credits',
      'awards_en': 'Awards',
      
      // Dashboard page
      'total_credits': 'Total Credits',
      'total_campaigns': 'Total Campaigns',
      'campaign_performance': 'Campaign Performance',
      'recent_activity': 'Recent Activity',
      'welcome_back': 'Welcome back',
      'whatsapp_campaigns_en': 'WhatsApp Campaigns',
      'view_all_en': 'View All',
      'create_new_en': 'Create New',
      'no_quizzes': 'No quizzes created yet',
      'create_your_first_quiz': 'Create your first quiz to start capturing leads',
      'quiz_performance': 'Quiz Performance',
      'leads_captured': 'Leads Captured',
      'completion_rate': 'Completion Rate',
      'average_time': 'Average Time',
      'top_performing': 'Top Performing',
      'views': 'Views',
      'responses': 'Responses',
      'edit_quiz': 'Edit Quiz',
      'view_quiz': 'View Quiz',
      'share_quiz': 'Share Quiz',
      'delete_quiz': 'Delete Quiz',
      'copy_link': 'Copy Link',
      'quiz_analytics': 'Quiz Analytics',
      'marketing_tools': 'Marketing Tools',
      'create_campaign': 'Create Campaign',
      'send_sms': 'Send SMS',
      'send_email': 'Send Email',
      'send_whatsapp': 'Send WhatsApp',
    },
    'es-ES': {
      // Sidebar
      'dashboard': 'Panel de Control',
      'create_quiz': 'Crear Quiz',
      'my_quizzes': 'Mis Quizzes',
      'analytics': 'Analíticas',
      'real_time_analytics': 'Analíticas en Tiempo Real',
      'email_marketing': 'Email Marketing',
      'sms_campaigns': 'Campañas SMS',
      'whatsapp_automation': 'Automatización WhatsApp',
      'cloaker': 'Cloaker',
      'upgrade': 'Actualizar',
      'settings': 'Configuraciones',
      'awards': 'Premios',
      'current_plan': 'Plan Actual',
      'quizzes_created': 'quizzes creados',
      'unlimited': 'ilimitado',
      'quizzes_used': 'quizzes utilizados',
      
      // Dashboard
      'welcome_back': '¡Bienvenido de vuelta!',
      'dashboard_subtitle': 'Rastrea el rendimiento de tus quizzes',
      'total_quizzes': 'Total de Quizzes',
      'total_views': 'Total de Visualizaciones',
      'total_leads': 'Total de Leads',
      'conversion_rate': 'Tasa de Conversión',
      'your_quizzes': 'Tus Quizzes',
      'quick_buttons': 'Botones Rápidos',
      'create_quiz_btn': 'Crear Quiz',
      'view_analytics': 'Ver Analíticas',
      'tutorials': 'Tutoriales',
      'plans': 'Planes',
      'marketing_automation': 'Automatización de Marketing',
      'email_campaigns': 'Campañas Email',
      'sms_marketing': 'Marketing SMS',
      'whatsapp_campaigns': 'Campañas WhatsApp',
      'quick_actions': 'Acciones Rápidas',
      'import_contacts': 'Importar Contactos',
      'export_data': 'Exportar Datos',
      'integrations': 'Integraciones',
      'api_settings': 'Configuraciones API',
      
      // Common
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'view': 'Ver',
      'create': 'Crear',
      'update': 'Actualizar',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'sort': 'Ordenar',
      'export': 'Exportar',
      'import': 'Importar',
      'close': 'Cerrar',
      'open': 'Abrir',
      'yes': 'Sí',
      'no': 'No',
      'back': 'Atrás',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'finish': 'Finalizar',
      'continue': 'Continuar',
      
      // Notifications
      'welcome_notification': '¡Bienvenido a Vendzz!',
      'account_created': 'Tu cuenta ha sido creada exitosamente. Explora las funcionalidades de la plataforma.',
      'system_updated': 'Sistema Actualizado',
      'new_version_available': 'Nueva versión disponible con mejoras de rendimiento.',
      'sms_credits': 'Créditos SMS',
      'credits_available': 'Tienes {credits} créditos SMS disponibles para tus campañas.',
      'remarketing_sms': 'SMS Remarketing',
      'templates': 'Plantillas',
      'admin': 'Admin',
      'current_plan_es': 'Plan Actual',
      'upgrade_es': 'Actualizar',
      'settings_es': 'Configuraciones',
      'credits_es': 'Créditos',
      'awards_es': 'Premios',
      
      // Dashboard page
      'total_credits': 'Total de Créditos',
      'total_campaigns': 'Total de Campañas',
      'campaign_performance': 'Rendimiento de Campañas',
      'recent_activity': 'Actividad Reciente',
      'welcome_back_es': 'Bienvenido de vuelta',
      'sms_campaigns_es': 'Campañas SMS',
      'whatsapp_campaigns_es': 'Campañas WhatsApp',
      'email_campaigns_es': 'Campañas Email',
      'view_all': 'Ver Todos',
      'create_new': 'Crear Nuevo',
      'no_quizzes': 'Ningún quiz creado aún',
      'create_your_first_quiz': 'Crea tu primer quiz para comenzar a capturar leads',
      'quiz_performance': 'Rendimiento de Quizzes',
      'leads_captured': 'Leads Capturados',
      'completion_rate': 'Tasa de Conclusión',
      'average_time': 'Tiempo Promedio',
      'top_performing': 'Mejor Rendimiento',
      'views': 'Visualizaciones',
      'responses': 'Respuestas',
      'edit_quiz': 'Editar Quiz',
      'view_quiz': 'Ver Quiz',
      'share_quiz': 'Compartir Quiz',
      'delete_quiz': 'Eliminar Quiz',
      'copy_link': 'Copiar Enlace',
      'quiz_analytics': 'Analytics del Quiz',
      'marketing_tools': 'Herramientas de Marketing',
      'quick_actions_duplicate': 'Acciones Rápidas',
      'create_campaign': 'Crear Campaña',
      'send_sms': 'Enviar SMS',
      'send_email': 'Enviar Email',
      'send_whatsapp': 'Enviar WhatsApp',
    },
    'fr-FR': {
      // Sidebar
      'dashboard': 'Tableau de Bord',
      'create_quiz': 'Créer Quiz',
      'my_quizzes': 'Mes Quizzes',
      'analytics': 'Analytiques',
      'real_time_analytics': 'Analytiques en Temps Réel',
      'email_marketing': 'Email Marketing',
      'sms_campaigns': 'Campagnes SMS',
      'whatsapp_automation': 'Automatisation WhatsApp',
      'cloaker': 'Cloaker',
      'upgrade': 'Mise à Niveau',
      'settings': 'Paramètres',
      'awards': 'Récompenses',
      'current_plan_fr': 'Plan Actuel',
      'quizzes_created': 'quizzes créés',
      'unlimited': 'illimité',
      'quizzes_used': 'quizzes utilisés',
      
      // Dashboard
      'welcome_back': 'Bon retour!',
      'dashboard_subtitle': 'Suivez les performances de vos quizzes',
      'total_quizzes': 'Total des Quizzes',
      'total_views': 'Total des Vues',
      'total_leads': 'Total des Leads',
      'conversion_rate': 'Taux de Conversion',
      'your_quizzes': 'Vos Quizzes',
      'quick_buttons': 'Boutons Rapides',
      'create_quiz_btn': 'Créer Quiz',
      'view_analytics': 'Voir Analytiques',
      'tutorials': 'Tutoriels',
      'plans': 'Plans',
      'marketing_automation': 'Automatisation Marketing',
      'email_campaigns': 'Campagnes Email',
      'sms_marketing': 'Marketing SMS',
      'whatsapp_campaigns': 'Campagnes WhatsApp',
      'quick_actions': 'Actions Rapides',
      'import_contacts': 'Importer Contacts',
      'export_data': 'Exporter Données',
      'integrations': 'Intégrations',
      'api_settings': 'Paramètres API',
      
      // Common
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'cancel': 'Annuler',
      'save': 'Sauvegarder',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'view': 'Voir',
      'create': 'Créer',
      'update': 'Mettre à jour',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'sort': 'Trier',
      'export': 'Exporter',
      'import': 'Importer',
      'close': 'Fermer',
      'open': 'Ouvrir',
      'yes': 'Oui',
      'no': 'Non',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'finish': 'Terminer',
      'continue': 'Continuer',
      
      // Notifications
      'welcome_notification': 'Bienvenue sur Vendzz!',
      'account_created': 'Votre compte a été créé avec succès. Explorez les fonctionnalités de la plateforme.',
      'system_updated': 'Système Mis à Jour',
      'new_version_available': 'Nouvelle version disponible avec des améliorations de performance.',
      'sms_credits': 'Crédits SMS',
      'credits_available': 'Vous avez {credits} crédits SMS disponibles pour vos campagnes.',
      'remarketing_sms': 'SMS Remarketing',
      'templates': 'Modèles',
      'admin': 'Admin',
      
      // Dashboard page
      'total_credits': 'Total des Crédits',
      'total_campaigns': 'Total des Campagnes',
      'campaign_performance': 'Performance des Campagnes',
      'recent_activity': 'Activité Récente',
      'view_all': 'Voir Tout',
      'create_new': 'Créer Nouveau',
      'no_quizzes': 'Aucun quiz créé encore',
      'create_your_first_quiz': 'Créez votre premier quiz pour commencer à capturer des leads',
      'quiz_performance': 'Performance des Quizzes',
      'leads_captured': 'Leads Capturés',
      'completion_rate': 'Taux de Completion',
      'average_time': 'Temps Moyen',
      'top_performing': 'Meilleure Performance',
      'views': 'Vues',
      'responses': 'Réponses',
      'edit_quiz': 'Modifier Quiz',
      'view_quiz': 'Voir Quiz',
      'share_quiz': 'Partager Quiz',
      'delete_quiz': 'Supprimer Quiz',
      'copy_link': 'Copier Lien',
      'quiz_analytics': 'Analytics du Quiz',
      'marketing_tools': 'Outils Marketing',
      'create_campaign': 'Créer Campagne',
      'send_sms': 'Envoyer SMS',
      'send_email': 'Envoyer Email',
      'send_whatsapp': 'Envoyer WhatsApp'
    }
  };

  const langTranslations = translations[language] || translations['pt-BR'];
  let translation = langTranslations[key] || key;

  // Replace parameters if provided
  if (params) {
    Object.entries(params).forEach(([param, value]) => {
      translation = translation.replace(`{${param}}`, value);
    });
  }

  return translation;
}