import { useState, useEffect } from "react";

// Traduções centralizadas
const translations = {
  'pt-BR': {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalQuizzes': 'Total de Quizzes',
    'dashboard.totalLeads': 'Total de Leads',
    'dashboard.totalViews': 'Total de Visualizações',
    'dashboard.conversionRate': 'Taxa de Conversão',
    'dashboard.yourQuizzes': 'Seus Quizzes',
    'dashboard.viewAll': 'Ver Todos',
    'dashboard.published': 'Publicado',
    'dashboard.draft': 'Rascunho',
    'dashboard.edit': 'Editar',
    'dashboard.preview': 'Visualizar',
    'dashboard.views': 'visualizações',
    'dashboard.smsCampaigns': 'Campanhas SMS',
    'dashboard.emailCampaigns': 'Campanhas Email',
    'dashboard.whatsappCampaigns': 'Campanhas WhatsApp',
    'dashboard.createFirstQuiz': 'Criar Primeiro Quiz',
    'dashboard.noQuizzes': 'Nenhum quiz encontrado',
    'dashboard.upgradeAccount': 'Atualizar Conta',
    'dashboard.viewAnalytics': 'Analytics',
    'dashboard.settings': 'Configurações',
    
    // SMS
    'sms.availableCredits': 'Créditos Disponíveis',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.performance': 'Performance',
    'analytics.impressions': 'Impressões',
    'analytics.clicks': 'Cliques',
    'analytics.conversions': 'Conversões',
    'analytics.revenue': 'Receita',
    'analytics.totalQuizzes': 'Total de Quizzes',
    'analytics.totalLeads': 'Total de Leads',
    'analytics.totalViews': 'Total de Visualizações',
    'analytics.conversionRate': 'Taxa de Conversão',
    'analytics.averageTime': 'Tempo Médio',
    'analytics.bounceRate': 'Taxa de Rejeição',
    'analytics.topPerforming': 'Melhor Performance',
    'analytics.growth': 'Crescimento',
    'analytics.engagement': 'Engajamento',
    'analytics.retention': 'Retenção',
    'analytics.segments': 'Segmentos',
    'analytics.filters': 'Filtros',
    'analytics.refresh': 'Atualizar',
    
    // Email Marketing
    'emailMarketing.title': 'Email Marketing',
    'emailMarketing.description': 'Gerencie campanhas de email para seus leads',
    
    // Quiz Editor
    'quizEditor.title': 'Editor de Quiz',
    'quizEditor.save': 'Salvar',
    'quizEditor.publish': 'Publicar',
    'quizEditor.preview': 'Visualizar',
    'quizEditor.settings': 'Configurações',
    'quizEditor.addPage': 'Adicionar Página',
    'quizEditor.addElement': 'Adicionar Elemento',
    'quizEditor.properties': 'Propriedades',
    'quizEditor.testAB': 'Teste A/B',
    'quizEditor.design': 'Design',
    'quizEditor.flow': 'Fluxo',
    'quizEditor.variables': 'Variáveis',
    'quizEditor.integrations': 'Integrações',
    'quizEditor.pageTitle': 'Título da Página',
    'quizEditor.required': 'Obrigatório',
    'quizEditor.placeholder': 'Placeholder',
    'quizEditor.buttonText': 'Texto do Botão',
    'quizEditor.fontSize': 'Tamanho da Fonte',
    'quizEditor.textAlign': 'Alinhamento',
    'quizEditor.color': 'Cor',
    'quizEditor.backgroundColor': 'Cor de Fundo',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Faça login em sua conta',
    'login.login': 'Entrar',
    'login.register': 'Registrar',
    'login.email': 'Email',
    'login.password': 'Senha',
    'login.rememberPassword': 'Lembrar senha',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.firstName': 'Nome',
    'login.lastName': 'Sobrenome',
    'login.whatsapp': 'WhatsApp',
    'login.confirmPassword': 'Confirmar Senha',
    'login.captcha': 'Captcha',
    'login.human': 'Sou humano',
    'login.loginSuccess': 'Login realizado com sucesso!',
    'login.loginError': 'Erro no login',
    'login.registerSuccess': 'Conta criada com sucesso!',
    'login.fillAllFields': 'Preencha todos os campos',
    'login.passwordMismatch': 'As senhas não coincidem',
    'login.wrongCaptcha': 'Resposta do captcha incorreta',
    'login.loading': 'Carregando...',
    'login.createAccount': 'Criar conta',
    'login.backToLogin': 'Voltar ao login',
    'login.enterDetails': 'Digite seus dados abaixo',
    'login.signUp': 'Cadastrar',
    'login.signIn': 'Entrar',
    'login.welcomeBack': 'Bem-vindo de volta',
    'login.createNewAccount': 'Criar nova conta',
    'login.alreadyHaveAccount': 'Já tem uma conta?',
    'login.dontHaveAccount': 'Não tem uma conta?',
    
    // Sidebar
    'sidebar.creation': 'CRIAÇÃO',
    'sidebar.recurring': 'RECURRING',
    'sidebar.analytics': 'ANALYTICS',
    'sidebar.campaigns': 'CAMPANHAS',
    'sidebar.integrations': 'INTEGRAÇÕES',
    'sidebar.advanced': 'AVANÇADO',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.quizBuilder': 'Quiz Builder',
    'sidebar.templates': 'Templates',
    'sidebar.abTesting': 'Teste A/B',
    'sidebar.tracking': 'Tracking',
    'sidebar.smsMarketing': 'SMS Marketing',
    'sidebar.emailMarketing': 'Email Marketing',
    'sidebar.whatsappBusiness': 'WhatsApp Business',
    'sidebar.apiWebhooks': 'API & Webhooks',
    'sidebar.variables': 'Variáveis',
    'sidebar.flowBuilder': 'Flow Builder',
    'sidebar.aiConversion': 'I.A. Conversion',
    'sidebar.facelessVideos': 'Faceless Videos',
    'sidebar.design': 'Design',
    'sidebar.multiplayer': 'Multiplayer',
    'sidebar.security': 'Segurança',
    'sidebar.settings': 'Configurações',
    'sidebar.plans': 'Planos',
    'sidebar.credits': 'Créditos',
    'sidebar.officialCheckout': 'Checkout Oficial',
    'sidebar.managePlans': 'Gerenciar Planos',
    'sidebar.checkoutSystem': 'Sistema Checkout',
    'sidebar.individualCheckout': 'Checkout Individual',
    'sidebar.productBuilder': 'Product Builder',
    'sidebar.manageSubscriptions': 'Gerenciar Assinaturas',
    'sidebar.telegram': 'Telegram',
    'sidebar.voiceMarketing': 'Voice Marketing',
    'sidebar.superAffiliates': 'Super Afiliados',
    'sidebar.conditionalCampaigns': 'Campanhas Condicionais',
    'sidebar.webhooks': 'Webhooks',
    'sidebar.extensions': 'Extensões',
    'sidebar.cloaker': 'Cloaker',
    'sidebar.upgrade': 'Upgrade',
    
    // Quiz Builder
    'quizBuilder.save': 'Salvar',
    'quizBuilder.saving': 'Salvando...',
    'quizBuilder.publish': 'Publicar',
    'quizBuilder.publishing': 'Publicando...',
    'quizBuilder.preview': 'Visualizar',
    'quizBuilder.tabs.editor': 'Editor',
    'quizBuilder.tabs.preview': 'Visualizar',
    'quizBuilder.tabs.flow': 'Fluxo Avançado',
    'quizBuilder.tabs.design': 'Design',
    'quizBuilder.tabs.settings': 'Configurações',
    'quizBuilder.tabs.abTest': 'Teste A/B',
    'quizBuilder.tabs.pixels': 'Pixels/Scripts',
    'quizBuilder.tabs.blackhat': 'BlackHat',
    'quizBuilder.messages.quizSaved': 'Quiz salvo com sucesso',
    'quizBuilder.messages.errorSaving': 'Erro ao salvar o quiz',
    'quizBuilder.messages.titleRequired': 'Título obrigatório',
    'quizBuilder.messages.titleRequiredDesc': 'Por favor, adicione um título para o quiz na aba "Configurações" antes de salvar.',
    'quizBuilder.messages.accessDenied': 'Acesso negado',
    'quizBuilder.messages.accessDeniedDesc': 'Você precisa estar logado para acessar o editor.',
    'quizBuilder.messages.unauthorized': 'Acesso Negado',
    'quizBuilder.messages.unauthorizedDesc': 'Você foi desconectado. Redirecionando para login...',
    
    // Templates
    'templates.title': 'Templates de Quiz',
    'templates.subtitle': 'Escolha um template para começar rapidamente seu quiz personalizado',
    'templates.search': 'Buscar templates...',
    'templates.category': 'Categoria',
    'templates.difficulty': 'Dificuldade',
    'templates.allCategories': 'Todas as Categorias',
    'templates.allDifficulties': 'Todas as Dificuldades',
    'templates.useTemplate': 'Usar Template',
    'templates.preview': 'Visualizar',
    'templates.categories': {
      'leadGeneration': 'Geração de Leads',
      'product': 'Produto',
      'personality': 'Personalidade',
      'knowledge': 'Conhecimento',
      'feedback': 'Feedback',
      'segmentation': 'Segmentação'
    },
    'templates.difficulties': {
      'easy': 'Fácil',
      'medium': 'Médio',
      'hard': 'Difícil'
    },
    
    // Common
    'common.create_quiz_btn': 'Criar Quiz',
    'common.upgrade': 'Fazer Upgrade',
    'common.current_plan': 'Plano Atual',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Deletar',
    'common.edit': 'Editar',
    'common.view': 'Visualizar',
    'common.create': 'Criar',
    'common.update': 'Atualizar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.close': 'Fechar',
    'common.open': 'Abrir',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.finish': 'Finalizar',
    'common.continue': 'Continuar',
  },
  
  'en-US': {
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.totalQuizzes': 'Total Quizzes',
    'dashboard.totalLeads': 'Total Leads',
    'dashboard.totalViews': 'Total Views',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.yourQuizzes': 'Your Quizzes',
    'dashboard.viewAll': 'View All',
    'dashboard.published': 'Published',
    'dashboard.draft': 'Draft',
    'dashboard.edit': 'Edit',
    'dashboard.preview': 'Preview',
    'dashboard.views': 'views',
    'dashboard.smsCampaigns': 'SMS Campaigns',
    'dashboard.emailCampaigns': 'Email Campaigns',
    'dashboard.whatsappCampaigns': 'WhatsApp Campaigns',
    'dashboard.createFirstQuiz': 'Create First Quiz',
    'dashboard.noQuizzes': 'No quizzes found',
    'dashboard.upgradeAccount': 'Upgrade Account',
    'dashboard.viewAnalytics': 'Analytics',
    'dashboard.settings': 'Settings',
    
    // SMS
    'sms.availableCredits': 'Available Credits',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.performance': 'Performance',
    'analytics.impressions': 'Impressions',
    'analytics.clicks': 'Clicks',
    'analytics.conversions': 'Conversions',
    'analytics.revenue': 'Revenue',
    'analytics.totalQuizzes': 'Total Quizzes',
    'analytics.totalLeads': 'Total Leads',
    'analytics.totalViews': 'Total Views',
    'analytics.conversionRate': 'Conversion Rate',
    'analytics.averageTime': 'Average Time',
    'analytics.bounceRate': 'Bounce Rate',
    'analytics.topPerforming': 'Top Performing',
    'analytics.growth': 'Growth',
    'analytics.engagement': 'Engagement',
    'analytics.retention': 'Retention',
    'analytics.segments': 'Segments',
    'analytics.filters': 'Filters',
    'analytics.refresh': 'Refresh',
    
    // Email Marketing
    'emailMarketing.title': 'Email Marketing',
    'emailMarketing.description': 'Manage email campaigns for your leads',
    
    // Quiz Editor
    'quizEditor.title': 'Quiz Editor',
    'quizEditor.save': 'Save',
    'quizEditor.publish': 'Publish',
    'quizEditor.preview': 'Preview',
    'quizEditor.settings': 'Settings',
    'quizEditor.addPage': 'Add Page',
    'quizEditor.addElement': 'Add Element',
    'quizEditor.properties': 'Properties',
    'quizEditor.testAB': 'A/B Test',
    'quizEditor.design': 'Design',
    'quizEditor.flow': 'Flow',
    'quizEditor.variables': 'Variables',
    'quizEditor.integrations': 'Integrations',
    'quizEditor.pageTitle': 'Page Title',
    'quizEditor.required': 'Required',
    'quizEditor.placeholder': 'Placeholder',
    'quizEditor.buttonText': 'Button Text',
    'quizEditor.fontSize': 'Font Size',
    'quizEditor.textAlign': 'Text Align',
    'quizEditor.color': 'Color',
    'quizEditor.backgroundColor': 'Background Color',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Sign in to your account',
    'login.login': 'Sign In',
    'login.register': 'Register',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.rememberPassword': 'Remember password',
    'login.forgotPassword': 'Forgot password?',
    'login.firstName': 'First Name',
    'login.lastName': 'Last Name',
    'login.whatsapp': 'WhatsApp',
    'login.confirmPassword': 'Confirm Password',
    'login.captcha': 'Captcha',
    'login.human': 'I am human',
    'login.loginSuccess': 'Login successful!',
    'login.loginError': 'Login error',
    'login.registerSuccess': 'Account created successfully!',
    'login.fillAllFields': 'Please fill all fields',
    'login.passwordMismatch': 'Passwords do not match',
    'login.wrongCaptcha': 'Wrong captcha answer',
    'login.loading': 'Loading...',
    'login.createAccount': 'Create account',
    'login.backToLogin': 'Back to login',
    'login.enterDetails': 'Enter your details below',
    'login.signUp': 'Sign Up',
    'login.signIn': 'Sign In',
    'login.welcomeBack': 'Welcome back',
    'login.createNewAccount': 'Create new account',
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.dontHaveAccount': 'Don\'t have an account?',
    
    // Sidebar
    'sidebar.creation': 'CREATION',
    'sidebar.recurring': 'RECURRING',
    'sidebar.analytics': 'ANALYTICS',
    'sidebar.campaigns': 'CAMPAIGNS',
    'sidebar.integrations': 'INTEGRATIONS',
    'sidebar.advanced': 'ADVANCED',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.quizBuilder': 'Quiz Builder',
    'sidebar.templates': 'Templates',
    'sidebar.abTesting': 'A/B Test',
    'sidebar.tracking': 'Tracking',
    'sidebar.smsMarketing': 'SMS Marketing',
    'sidebar.emailMarketing': 'Email Marketing',
    'sidebar.whatsappBusiness': 'WhatsApp Business',
    'sidebar.apiWebhooks': 'API & Webhooks',
    'sidebar.variables': 'Variables',
    'sidebar.flowBuilder': 'Flow Builder',
    'sidebar.aiConversion': 'A.I. Conversion',
    'sidebar.facelessVideos': 'Faceless Videos',
    'sidebar.design': 'Design',
    'sidebar.multiplayer': 'Multiplayer',
    'sidebar.security': 'Security',
    'sidebar.settings': 'Settings',
    'sidebar.plans': 'Plans',
    'sidebar.credits': 'Credits',
    'sidebar.officialCheckout': 'Official Checkout',
    'sidebar.managePlans': 'Manage Plans',
    'sidebar.checkoutSystem': 'Checkout System',
    'sidebar.individualCheckout': 'Individual Checkout',
    'sidebar.productBuilder': 'Product Builder',
    'sidebar.manageSubscriptions': 'Manage Subscriptions',
    'sidebar.telegram': 'Telegram',
    'sidebar.voiceMarketing': 'Voice Marketing',
    'sidebar.superAffiliates': 'Super Affiliates',
    'sidebar.conditionalCampaigns': 'Conditional Campaigns',
    'sidebar.webhooks': 'Webhooks',
    'sidebar.extensions': 'Extensions',
    'sidebar.cloaker': 'Cloaker',
    'sidebar.upgrade': 'Upgrade',
    
    // Templates
    'templates.title': 'Quiz Templates',
    'templates.subtitle': 'Choose a template to quickly start your customized quiz',
    'templates.search': 'Search templates...',
    'templates.category': 'Category',
    'templates.difficulty': 'Difficulty',
    'templates.allCategories': 'All Categories',
    'templates.allDifficulties': 'All Difficulties',
    'templates.useTemplate': 'Use Template',
    'templates.preview': 'Preview',
    'templates.categories': {
      'leadGeneration': 'Lead Generation',
      'product': 'Product',
      'personality': 'Personality',
      'knowledge': 'Knowledge',
      'feedback': 'Feedback',
      'segmentation': 'Segmentation'
    },
    'templates.difficulties': {
      'easy': 'Easy',
      'medium': 'Medium',
      'hard': 'Hard'
    },
    
    // Common
    'common.create_quiz_btn': 'Create Quiz',
    'common.upgrade': 'Upgrade',
    'common.current_plan': 'Current Plan',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.continue': 'Continue',
  }
};

export function useLanguage() {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    return localStorage.getItem('vendzz-language') || 'pt-BR';
  });

  const changeLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('vendzz-language', language);
  };

  const t = (key: string, params?: Record<string, string>) => {
    const translation = translations[currentLanguage as keyof typeof translations]?.[key] || key;
    
    if (params) {
      return Object.keys(params).reduce((acc, param) => {
        return acc.replace(`{${param}}`, params[param]);
      }, translation);
    }
    
    return translation;
  };

  return { currentLanguage, changeLanguage, t };
}